### ISSUE TITLE
Calling buffer_initialize() fails

### ISSUE THREAD

**Issue by jaap-karssenberg** [koehlma/pygtkspellcheck#24]
Traceback (most recent call last):
      
     File "/home/jaap/code/zim-trunk/zim/plugins/spell.py", line 140, in on_open_page
        checker.on_new_buffer()
      File "/home/jaap/code/zim-trunk/zim/plugins/spell.py", line 189, in on_new_buffer
        self._checker.buffer_initialize()
      File "/usr/lib/python2.7/dist-packages/gtkspellcheck/spellcheck.py", line 219, in buffer_initialize
        self._table.add(self._misspelled)
    ValueError: The tag is already in a tag table

My suggestion is to re-initialize "self._misspelled" in buffer_initialize. The old buffer may still exist, e.g. not yet garbage collected.

Thanks,

Jaap

**Comment by jaap-karssenberg** [comment]
Work around is to instantiate a new SpellChecker. However after disabling and removing the old one, the gtkspellchecker- tags remain in the tagtable. Need to remove those as well before instantiating the new one. But this works fine for now.

Regards,

Jaap

**Comment by koehlma** [comment]
Does this fix the problem?

**Comment by jaap-karssenberg** [comment]
Looks OK to me. Probably best to have a unittest case that test re-initializing the buffer.

If you want I could write a small test case for the things I encountered and submit a patch?

Regards,

Jaap
