### ISSUE TITLE
Using other dictionary

### ISSUE THREAD

**Issue by MarkKavanagh** [koehlma/pygtkspellcheck#25]
Hi, I've scoured the documents but I cannot for the life of me figure out how to use another dictionary.
I have the en_GB.aff and en_GB.dic files. Do they need to be placed in a particular folder?

Thanks for making this! It's a pretty cool project!

**Comment by koehlma** [comment]
Hi, have a look at the `params` argument of `SpellChecker`. It allows you to set enchant broker parameters: http://pygtkspellcheck.readthedocs.io/en/latest/#gtkspellcheck.spellcheck.SpellChecker

I think you have to set the property `enchant.myspell.dictionary.path` to the appropriate path containing the dictionary files.

**Comment by MarkKavanagh** [comment]
Hi Max,
Like this?

spellchecker=SpellChecker(self.Email_Message,language='en_GB',collapse=False,enchant.set_param("enchant.myspell.dictionary.path","../modules/koehlma-pygtkspellcheck-ce2e62d/Dictionary/")

self.Email_Message is textview, and
"../modules/koehlma-pygtkspellcheck-ce2e62d/Dictionary/" is the relative
path to the dictionary.

Thanks!
Mark

**Comment by MarkKavanagh** [comment]
Ok, so I've done a bit of reading and experimenting:

Broker=enchant.Broker()      #Create a Broker

Broker.set_param("enchant.myspell.dictionary.path","./modules/koehlma-pygtkspellcheck-ce2e62d/Dictionary/")
         #Point Broker to en_GB dictionary folder

Dict=enchant.Dict('en_GB',Broker)    #Create en_GB dictionary - confirmed
it is en_GB

#Two Variations on spellchecker

spellchecker=SpellChecker(self.Email_Message,language=Dict,collapse=False)
 #Still en_US

spellchecker=SpellChecker(self.Email_Message,language='en_GB',collapse=False,Params=Dict)
#Throws an error...

#Error Message
for param, value in params.items(): self._broker.set_param(param, value)
AttributeError: 'Dict' object has no attribute 'items'

getting closer!

**Comment by koehlma** [comment]
Try this:
```python
spellchecker = SpellChecker(…, params={'enchant.myspell.dictionary.path': '../modules/koehlma-pygtkspellcheck-ce2e62d/Dictionary/'})
```

**Comment by MarkKavanagh** [comment]
Figured it out! For anyone else who wants the solution, 
here's a bare bones layout.

`#Load Packages`
`import enchant, locale, sys, gtk`
`#src Folder of pygtkspellcheck`
`sys.path.insert(0,'<Directory>/koehlma-pygtkspellcheck-ce2e62d/src')`
`#Load pygtkspellcheck`
`from gtkspellcheck import SpellChecker`
` `
`#Insert you GTK code... windows, buttons, etc...`
`#The textview for spell checking`
`view = gtk.TextView()`
`#Paramters inf the form parameters={'Parameter1' : 'Value1','Parameter2' : 'Value2'}
`#Only one parameter...the folder where my dictionary (en_GB) resides`
`parameters={"enchant.myspell.dictionary.path": "<Path-To-Folder-With-Dictionary>"}`
`#Create the spell checker
spellchecker = SpellChecker(view,'en_GB', collapse=True,params=parameters)

Note the paths can be absolute or relative

**Comment by MarkKavanagh** [comment]
haha I had just figured it out on my own by looking at your code in detail!
Thanks for the help!

**Comment by koehlma** [comment]
You are welcome. By the way, you might have a look at [PEP8](https://www.python.org/dev/peps/pep-0008/) especially if you are new to Python. Sticking to the style guide would make your code much more readable for other people. ;)

**Comment by MarkKavanagh** [comment]
More so new to git... I had replied from my email (since it came to my inbox),
I won't make that mistake again, but I'll take peek at the PEP8, could prove useful!
