### ISSUE TITLE
Move oxt_extract to separate repo

### ISSUE THREAD

**Issue by jendrikseipp** [koehlma/pygtkspellcheck#28]
In my opinion the `oxt_extract` library and helper script should be maintained in a separate repository. They are independent from pygtkspellcheck and are useful even for people who don't use pygtkspellcheck. The separation would make this repo cleaner, the documentation simpler and version upgrades for both projects easier.

**Comment by koehlma** [comment]
Sounds like a good idea to me. However I am not willing to break backward compatibility again. Therefore I will postpone this until there is a good reason to break the API anyway.

**Comment by koehlma** [comment]
The `oxt_extract` module has been removed with version 5.0.

At this point, I do not plan to move it to a separate repository. As far as I can tell, all projects only depend on the main spellchecking API anyway and no one is using the `oxt_extract` API. Sure, this may be useful for someone on its own, however, I am not willing to put in the maintenance effort that comes with a separate project.
