### ISSUE TITLE
Installation using pip fails if pyenchant has never been installed

### ISSUE THREAD

**Issue by gnarlyquack** [koehlma/pygtkspellcheck#36]
This appears to happen because setup.py imports gtkspellcheck, which imports spellcheck, which imports enchant, which causes installation to fail with an ImportError. This can be masked if pyenchant has been previously installed and is in pip's local cache; wipe out the cache and pygtkspellcheck will fail to install.

**Comment by PanderMusubi** [comment]
Is this still an issue? On Ubuntu 19.10 this works:

    pip3 install pygtkspellcheck
