### ISSUE TITLE
Upgrade using new libgtkspell and enchant

### ISSUE THREAD

**Issue by PanderMusubi** [koehlma/pygtkspellcheck#40]
Please note that a new release of pygtkspellcheck should be aware that both libgtkspell and enchant have much newer versions. See also https://sourceforge.net/p/gtkspell/mailman/message/36911759/

**Comment by koehlma** [comment]
Note that Python GTK Spellcheck is completely independent of GtkSpell and as far as I am aware it should use the installed version of Enchant, whatever this version may be. So, what precisely do you mean?

**Comment by PanderMusubi** [comment]
Ha, i'm not exactly sure anymore why I reported this. Probably because I thought there was a dependency on gtkspell and/or the API in Enchant that changed a while ago. Fine to close this and sorry for the inconvenience.
