### ISSUE TITLE
Pasted input can result in false positives

### ISSUE THREAD

**Issue by cheywood** [koehlma/pygtkspellcheck#45]
I'm seeing an issue where pasted text which starts with non-word characters can trigger false positives, so long as it's not pasted into the start of the buffer. I first noticed this copying and pasting some checkbox list items, but it will trigger for other uses.

To reproduce:
1. Start with a new English buffer
2. Put something in the first line
3. Into the second line paste `- [ ] valid spelling`
4. Observe that `- [ ] valid` is marked incorrect
5. Start a new line
6. Type `- [ ] valid spelling`
7. Observe no false positives marked

Perhaps the fix is extending the current behaviour that `check_range` uses when the `start` iter is the start of the buffer, but I'm not entirely sure. Ideally a fix could make it in to the upcoming release.

**Comment by koehlma** [comment]
I do not recall why there has been this special case when starting at the beginning of the buffer. Do you have any idea?

I removed this special case and replaced it with something that hopefully makes more sense and should fix this issue also for cases where something is pasted not at the beginning of a line.

**Comment by cheywood** [comment]
> Do you have any idea?

Nope, and I like the look of what you've done :+1:
