### ISSUE TITLE
No installation instructions

### ISSUE THREAD

**Issue by introt** [koehlma/pygtkspellcheck#47]
Neither the README nor the RTD site have installation instructions, and the [PyPi project page](https://pypi.org/project/pygtkspellcheck/), which isn't linked to from either, looks a bit off with some broken text encoding.

(Also, while trying to establish whether this is the case for your other projects, I noticed that `racetrack` links to `momba`'s repository - might want to fix that as well.)

**Comment by koehlma** [comment]
Hey, thanks for reminding me about the outdated PyPi project page. :)

Installation instructions are a bit difficult to provide as they depend on the system. On some distributions, Python GTK Spellcheck is available via the package manager but in general it can be installed just like any other PyPi package. Do you have any specific suggestions how such instructions should look like?

With the upcoming release, I will replace this with the README file of this repository providing at least some further information and fixing the broken text encoding.

The `racetrack` package does not have its own repository but the website should indeed be replaced with a specific link to the documentation. Thanks for pointing that out. 👍

**Comment by introt** [comment]
You're welcome :)

A general "available on pip (and probs packaged by your distro with a weird name like `PyGTKSpell` or `python-gtkspell`)" would be satisfactory - though [even Sphinx omits the latter](https://github.com/sphinx-doc/sphinx/#installation=).

This'd let people know whether they need to clone the repo, or check their (system's) package manager as well as somewhat validate the authenticity of the PyPi package.

**Comment by koehlma** [comment]
Please have a look at the updated README.

**Comment by introt** [comment]
It's perfect, thank you!
