### ISSUE TITLE
Crash building menu with Gedit installed using GTK 4

### ISSUE THREAD

**Issue by cheywood** [koehlma/pygtkspellcheck#54]
Iotas installed as a system package is apparently [crashing building the menu when Gedit is installed](https://gitlab.gnome.org/World/iotas/-/issues/116). I seems to be related to borrowing translations from Gedit (... which I was obvious to when I helped with the GTK 4 port).

Time poor for the few weeks I haven't looked at this properly yet.

Issue copy below.

---

I have installed Iotas from an AUR package (https://aur.archlinux.org/packages/iotas) in order to utilize system dictionaries.
When I right click on a misspelled word in any language the app instantly crashes with a following output:

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gtkspellcheck/spellcheck.py", line 844, in _gtk4_on_textview_click
    self.populate_menu(self._spelling_menu)
  File "/usr/lib/python3.11/site-packages/gtkspellcheck/spellcheck.py", line 657, in populate_menu
    items = self._suggestion_menu(word)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gtkspellcheck/spellcheck.py", line 799, in _suggestion_menu
    add_to_dict_menu_label = _("Add to Dictionary")
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gtkspellcheck/spellcheck.py", line 80, in _
    return _gedit(_GEDIT_MAP[message]).replace("_", "")
                  ~~~~~~~~~~^^^^^^^^^
KeyError: 'Add to Dictionary'
```

**Comment by koehlma** [comment]
Just removing the `"{}"` in the following line should suffice:

https://github.com/koehlma/pygtkspellcheck/blob/17923aee49ea8d7245cc91154b81da5c4f034b22/src/gtkspellcheck/spellcheck.py#L68

**Comment by cheywood** [comment]
Perfect yes I had a quick look after submitting the issue and spotted the same. I also did a quick pass for any other non matching strings (and didn't find any). Will MR.

**Comment by cheywood** [comment]
This has been very briefly tested on a VM and resolves the crash.

Not tested is whether the GTK4 port has had any impact on the borrowed translations.

**Comment by koehlma** [comment]
Thanks, looks good.

I just published a new release with the fix.
